title: Bruja
intro: 'Um homem que vive em uma pequena casa, numa fazenda, se vê encurralado pela presença de uma mulher macabra. Noite após noite, ele consegue ouvi-la mais perto.'
updated_by: 44c4a4a6-a159-4f5d-b1f6-e4b5599a8488
updated_at: 1735853366
blueprint: coletanea
