title: 'O visitante'
intro: 'Toda noite, antes de dormir, a criança recebia um visitante indesejado em seu quarto. O ser, que não pertencia ao mundo de cá, parecia determinado a chegar até o garoto, desmembrar-lhe e comer seu coração. O problema é que ninguém mais parecia conseguir exergar esse visitante grotesco e maldoso.'
updated_by: 44c4a4a6-a159-4f5d-b1f6-e4b5599a8488
updated_at: 1735861201
blueprint: coletanea
